//
// Copyright (c) 2024, SkyFoundry LLC
// Licensed under the Academic Free License version 3.0
//
// History:
//   17 Jul 2024  Brian Frank  Creation
//   30 Aug 2026  Brian Frank  Move from ion pod
//

accordian=Accordian
action=Action
actions=Actions
activity=Activity
activities=Activities
add=Add
additional=Additional
admin=Admin
advanced=Advanced
agents=Agents
ai=AI
all=All
allow=Allow
amber=Amber
api=API
app=App
apps=Apps
arcbeam=Arcbeam
ascending=Ascending
attach=Attach
attachment=Attachment
auto=Auto
autocomplete=Autocomplete
autoActions=Type action name to search...
autoGoto=Type symbol or line number...
average=Average
axis.sec=k:mm:ssa
axis.min5=k:mma
axis.hour=ka
axis.hour6=DDD ka
axis.day=WWW DDD
axis.month=MMM
axis.year=YYYY

back=Back
backup=Backup
backups=Backups
bar=Bar
block=Block
blue=Blue
bold=Bold
bottom=Bottom
bubble=Bubble
build=Build
builder=Builder
by=By
byCity=By City
byEquip=By Equip
bySite=By Site
bySpace=By Space
bySpec=By Spec
byStateByCity=By State/City
bySystem=By System

cancel=Cancel
cancelled=Cancelled
cancelling=Cancelling
card=Card
cards=Cards
center=Center
change=Change
chart=Chart
charts=Charts
child=Child
choice=Choice
choices=Choices
choose=Choose
clear=Clear
close=Close
closed=Closed
closing=Closing
code=Code
color=Color
colors=Colors
column=Column
columns=Columns
comp=Comp
complete=Complete
comps=Comps
config=Config
conn=Conn
conns=Conns
connector=Connector
confirm=Confirm
constants=Constants
content=Content
control=Control
conversion=Conversion
conversations=Conversations
copilot=Copilot
copy=Copy
count=Count
created=Created
cut=Cut
cyan=Cyan

data=Data
date=Date
dates=Dates
day=Day
days=Days
debug=Debug
default=Default
delete=Delete
descending=Descending
density=Density
details=Details
develop=Develop
device=Device
devices=Devices
directory=Directory
disable=Disable
disabled=Disabled
doc=Doc
docs=Docs
done=Done
download=Download
draft=Draft
duplicate=Duplicate
duration=Duration

edit=Edit
editor=Editor
email=Email
emerald=Emerald
empty=Empty
end=End
enable=Enable
enabled=Enabled
engineer=Engineer
enum=Enum
equip=Equip
equips=Equips
error=Error
eval=Eval
eula=EULA
expires=Expires
explain=Explain
export=Export
expr=Expr

false=False
fault=Fault
file=File
fileInputDropZone=Drop here or click to browse
filename=Filename
files=Files
filter=Filter
find=Find
findInFiles=Find in Files
form=Form
format=Format
frame=Frame
frame.layout.title=Frame Layout
frame.layout.subtitle=Customize sidebar panels
from=From
fuchsia=Fuchsia
func=Func
funcs=Funcs
futureFailed=Operation failed

gauge=Gauge
glyphs=Glyphs
goTo=Go To
gotoLine=Go to line
goBack=Go Back
goForward=Go Forward
gray=Gray
green=Green
grid=Grid
group=Group
groups=Groups
grouping=Grouping
groupBy=Group By

hayson=Hayson
header=Header
heatMap=Heat Map
help=Help
hide=Hide
hidden=Hidden
history=History
historian=Historian
home=Home
host=Host
hour=Hour
http=HTTP
hvac=HVAC

icon=Icon
icons=Icons
id=Id
identity=Identity
idle=Idle
image=Image
images=Images
import=Import
info=Info
indigo=Indigo
input=Input
inputs=Inputs
insert=Insert
io=I/O
item=Item
items=Items

json=JSON
justify=Justify

keep=Keep
kpi=KPI
kpis=KPIs

latch=Latch
layout=Layout
left=Left
lens=Lens
level=Level
levels=Levels
license=License
lime=Lime
limit=Limit
link=Link
list=List
loading=Loading
locale=Locale
location=Location
logic=Logic

map=Map
markdown=Markdown
marker=Marker
markers=Markers
markerCols=Marker Columns
markerPills=Marker Pills
math=Math
max=Max
maxFiles=Max files
maxSize=Max size
menu=Menu
meta=Meta
min=Min
mockups=Mockups
models=Models
module=Module
modules=Modules
month=Month
moveDown=Move Down
moveLeft=Move Left
moveRight=Move Right
moveUp=Move Up
multiLine=Multi-Line
muted=Muted

name=Name
namespace=Namespace
needInput=Select input to load view
network=Network
networks=Networks
new=New
new.spec.title=Spec
new.spec.subtitle=Select type to create
new.template.title=Template
new.template.subtitle=Select template entities to create
new.edit.title=Edit
new.edit.subtitle=Edit tags for record to create
neutral=Neutral
next=Next
no=No
noData=No data
noResults=No results
noDataAppView=Select a type or instance
none=None
notebook=Notebook
normal=Normal

off=Off
ok=Ok
old=Old
on=On
open=Open
opening=Opening
operate=Operate
options=Options
orange=Orange
organizer=Organizer
orderAndVis=Order & Visibility
output=Output

palette=Palette
panel=Panel
paste=Paste
pattern=Pattern
pause=Pause
paused=Paused
pin=Pin
pinned=Pinned
ping=Ping
pink=Pink
pods=Pods
point=Point
points=Points
pointOverride=Point Override
portfolio=Portfolio
portfolios=Portfolios
primary=Primary
project=Project
projects=Projects
pull=Pull
purple=Purple
push=Push

quarter=Quarter
query=Query
quick=Quick

range=Range
rdf=RDF
reboot=Reboot
rebuild=Rebuild
rec=Rec
recs=Recs
recent=Recent
recompile=Recompile
recompute=Recompute
red=Red
redo=Redo
refresh=Refresh
relationships=Relationships
reload=Reload
remove=Remove
removeAll=Remove All
rename=Rename
reobserve=Reobserve
reopen=Reopen
reorder=Reorder
replace=Replace
replaceInFiles=Replace in Files
repo=Repo
repos=Repos
reset=Reset
right=Right
rollup=Rollup
row=Row
rows=Rows
rose=Rose
rule=Rule
rules=Rules
run=Run
running=Running
runtime=Runtime

same=Same
save=Save
schedule=Schedule
search=Search
secondary=Secondary
select=Select
selectAll=Select All
send=Send
settings=Settings
shell=Shell
show=Show
skills=Skills
sky=Sky
site=Site
sites=Sites
size=Size
slate=Slate
slots=Slots
sort=Sort
sorting=Sorting
source=Source
space=Space
spaces=Spaces
span=Span
spark=Spark
sparks=Sparks
spec=Spec
specs=Specs
split=Split
start=Start
status=Status
stone=Stone
string=String
styling=Styling
submit=Submit
subscriptions=Subscriptions
subtitle=Subtitle
success=Success
summary=Summary
sync=Sync
syncing=Syncing
system=System
systems=Systems

table=Table
tableConfig=Table Config
tableConfig.help=Update the configuration for columns and rows
tableConfig.orderAndVis.help=Column order and visibility
tableConfig.same.help=Hides column only when all the rows have the same value
tableConfig.sorting.help=Sort by columns
tableConfig.styling.help=Styling for columns, rows, and cells
tableConfig.visualization.help=Visualize a column graphically
tabs=Tabs
tag=Tag
tags=Tags
target=Target
targets=Targets
task=Task
tasks=Tasks
teal=Teal
test=Test
text=Text
theme=Theme
time=Time
timeout=Timeout
timestamp=Timestamp
title=Title
to=To
today=Today
toggleDebug=Toggle Debug
toggleDensity=Toggle Density
toggleTheme=Toggle Theme
toolbar=Toolbar
tools=Tools
top=Top
trash=Trash
tree=Tree
trio=Trio
true=True
type=Type
types=Types
timeZone=TimeZone

undo=Undo
unit=Unit
unpin=Unpin
update=Update
upload=Upload
user=User
username=Username
users=Users
util=Util

value=Value
values=Values
var=Var
variant=Variant
vars=Vars
view=View
views=Views
violet=Violet
visualize=Visualize
visualization=Visualization

warn=Warn
weather=Weather
weatherStation=Weather Station
weatherStations=Weather Stations
website=Website
week=Week
weekdays=Weekdays
weekend=Weekend
width=Width
woolly=Woolly

xeto=Xeto

year=Year
yellow=Yellow
yes=Yes
yesterday=Yesterday

zinc=Zinc

