services:
  haxall:
    stdin_open: true
    tty: true
    image: haxall
    container_name: haxall_run
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "${HAXALL_PORT:-8080}:8080"
    volumes:
      - ./dbs:/app/haxall/dbs
    environment:
      HAXALL_DB_NAME: ${HAXALL_DB_NAME:-var}
      HAXALL_SU_USERNAME: ${HAXALL_SU_USERNAME:-su}
      HAXALL_SU_PASSWORD: ${HAXALL_SU_PASSWORD:-}
